"""
universe.py
Stock universes for NSE — Large Cap, Mid Cap, Small Cap.
Sources: NSE index constituents (as of mid-2025).
"""

# ── LARGE CAP (Nifty 100) ──────────────────────────────────────────────────────
LARGE_CAP = [
    "ADANIENT","ADANIPORTS","APOLLOHOSP","ASIANPAINT","AXISBANK",
    "BAJAJ-AUTO","BAJFINANCE","BAJAJFINSV","BPCL","BHARTIARTL",
    "BRITANNIA","CIPLA","COALINDIA","DIVISLAB","DRREDDY",
    "EICHERMOT","GRASIM","HCLTECH","HDFCBANK","HDFCLIFE",
    "HEROMOTOCO","HINDALCO","HINDUNILVR","ICICIBANK","ITC",
    "INDUSINDBK","INFY","JSWSTEEL","KOTAKBANK","LT",
    "LTIM","M&M","MARUTI","NTPC","NESTLEIND",
    "ONGC","POWERGRID","RELIANCE","SBILIFE","SHRIRAMFIN",
    "SBIN","SUNPHARMA","TCS","TATACONSUM","TATAMOTORS",
    "TATASTEEL","TECHM","TITAN","ULTRACEMCO","WIPRO",
    "ABB","ADANIGREEN","AMBUJACEM","AUROPHARMA","BANKBARODA",
    "BERGEPAINT","BEL","BOSCHLTD","CHOLAFIN","COLPAL",
    "DABUR","DLF","GAIL","GODREJCP","HAL",
    "HAVELLS","ICICIGI","ICICIPRULI","INDHOTEL","IOC",
    "IRCTC","LICI","LUPIN","NHPC","OFSS",
    "PIDILITIND","RECLTD","SAIL","SIEMENS","TATAPOWER",
    "TORNTPHARM","TRENT","UPL","VEDL","ZYDUSLIFE",
]

# ── MID CAP (Nifty Midcap 150 sample) ─────────────────────────────────────────
MID_CAP = [
    "ABCAPITAL","ABFRL","ALKEM","APOLLOTYRE","ASHOKLEY",
    "ASTRAL","ATUL","AUBANK","BALKRISIND","BATAINDIA",
    "BHARATFORG","BIOCON","BSOFT","CANFINHOME","CASTROLIND",
    "CESC","CHAMBLFERT","COFORGE","CONCOR","CROMPTON",
    "CUMMINSIND","CYIENT","DEEPAKNTR","DIXON","ESCORTS",
    "EXIDEIND","FEDERALBNK","GMRAIRPORT","GNFC","GODREJIND",
    "GRANULES","GSPL","GUJGASLTD","HINDPETRO","IDFCFIRSTB",
    "IPCALAB","JKCEMENT","JUBILPHARMA","KAJARIACER","KANSAINER",
    "LICHSGFIN","LTTS","LUXIND","MARICO","MFSL",
    "METROPOLIS","MOTILALOFS","MRF","MUTHOOTFIN","NATIONALUM",
    "NAVINFLUOR","NBCC","NCC","NIACL","NMDC",
    "OBEROIRLTY","OFSS","PAGEIND","PEL","PERSISTENT",
    "PETRONET","PFC","PHOENIXLTD","POLYMED","PRESTIGE",
    "PRINCEPIPE","PVR","RAMCOCEM","RBLBANK","REDINGTON",
    "ROUTE","SAFARI","SJVN","SOLARINDS","SONACOMS",
    "STARHEALTH","SUPREMEIND","SYNGENE","TATACHEM","TATACOMM",
    "TATAELXSI","TIINDIA","TIMKEN","TORNTPOWER","TTKPRESTIG",
    "TVSMOTORS","UCOBANK","UNIONBANK","UBL","VGUARD",
    "VOLTAS","WHIRLPOOL","ZEEL","ZENSARTECH","ZENTEC",
]

# ── SMALL CAP (Nifty Smallcap 250 sample) ─────────────────────────────────────
SMALL_CAP = [
    "AFFLE","AGNITE","AJANTPHARM","ANGELONE","ANURAS",
    "APTUS","ARVINDFASN","ASAHIINDIA","ASKAUTOLTD","AVANTIFEED",
    "BAJAJHCARE","BALRAMCHIN","BASF","BBTC","BFUTILITIE",
    "BIKAJI","BLUESTARCO","CAMPUS","CANARA","CARBORUNIV",
    "CEATLTD","CENTURYPLY","CLEAN","CMSINFO","CONFIPET",
    "CRAFTSMAN","DATAPATTNS","DBCORP","DCAL","DELHIVERY",
    "DHANI","DOLLAR","DOMS","DREDGECORP","EASEMYTRIP",
    "ELECON","EMAMILTD","ENDURANCE","EPIGRAL","EQUITASBNK",
    "ETHOSINDIA","FINEORG","FINOFINANCE","FINPIPE","FLOREAT",
    "GABRIEL","GLENMARK","GPIL","GRINDWELL","GRSE",
    "HAPPSTMNDS","HEG","HEMIPROP","HINDCOPPER","HIMATSEIDE",
    "HOMEFIRST","IBREALEST","IDEAFORGE","IIFL","INDIAMART",
    "INDIAGLYCO","INDIGO","INOXWIND","INTELLECT","IONEXCHANG",
    "IREDA","JAMNAAUTO","JAYNECOIND","JBMA","JLHL",
    "JSWENERGY","JTEKIND","KALYANKJIL","KECL","KIMS",
    "KRISHNADEF","LATENTVIEW","LAXMIMACH","LEMONTREE","LGBBROSLTD",
    "MAHARASHTRA","MAHINDCIE","MANAPPURAM","MAPMYINDIA","MAYURUNIQ",
    "MEDANTA","MEDPLUS","MIDHANI","MIRCELECTR","MMTC",
    "MOLDTKPAC","MOTHERSON","MSTCLTD","NATCOPHARM","NAUKRI",
    "NAZARA","NSLNISP","NUCLEUS","OLECTRA","ORIENTELEC",
]

ALL_CAPS = {
    "largecap": LARGE_CAP,
    "midcap":   MID_CAP,
    "smallcap": SMALL_CAP,
}

def get_universe(cap_filter: str = "all") -> list:
    """
    cap_filter: "largecap" | "midcap" | "smallcap" | "all"
    """
    if cap_filter == "all":
        return list(dict.fromkeys(LARGE_CAP + MID_CAP + SMALL_CAP))
    return ALL_CAPS.get(cap_filter, LARGE_CAP)
